#!/bin/bash
# 
# rsync active worlds to remote server
# 
# USAGE:
# rsync-worlds [-1246Cqv] [-c cipher] [-F ssh_config] [-i identity] [-o option]
#              [-p port] [user@]hostname:remote_path
# 
# OPTIONS:
#     Options above are passed directly to the ssh command (via rsync)
# 
# Add a crontab entry for this script:
# 12 5 * * * minecraft /var/games/minecraft/scripts/rsync-worlds hostname path/on/remote
set -eo pipefail

MINECRAFT_SERVER_PATH="${MINECRAFT_SERVER_PATH:-/var/games/minecraft/servers/}"

main() {
	# Init variables
	local OPTION OPTARG OPTIND
	local rsync_dest rsh ssh_host ssh_path
	local -a ssh_opts
	
	# Parse options
	while getopts "1246Cc:F:i:o:p:qv" OPTION
	do
		#@TODO: Implement quiet and verbose
		# SSH options
		ssh_opts+=("-$OPTION")
		[[ -n "$OPTARG" ]] && ssh_opts+=("$OPTARG")
	done
	shift $((OPTIND-1))
	
	# Check for non-interactive mode
	if [[ ! $- = *i* ]]; then
		ssh_opts+=(-o "BatchMode=yes")
	fi
	
	rsync_dest="$1"
	rsh="ssh ${ssh_opts[@]}"
	IFS=: read -r ssh_host ssh_path <<< "$rsync_dest"
	if [[ -z "$ssh_host" || -z "$ssh_path" ]]; then
		echo "Error: hostname and remote path are required" >&2
		exit 1
	fi
	
	# Find active worlds and pass to rsync
	cd "$MINECRAFT_SERVER_PATH"
	find . -maxdepth 2 -type f -name active -printf '%h\0' | tee >/dev/null \
		>(xargs -0 -I{} sh -c "echo \"Backing up \$(basename \"{}\") to $ssh_host\"") \
		>(rsync -Ear --delete --safe-links --no-relative --rsh="$rsh" --files-from=- --from0 "$MINECRAFT_SERVER_PATH" "$rsync_dest")
}

if [[ ! -d "$MINECRAFT_SERVER_PATH" ]]; then
	echo "Error: Failed to load world storage directory" >&2
	echo "Make sure the MINECRAFT_SERVER_PATH env var is set" >&2
	exit 1
fi

main "$@"
